apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: flask-namespace
spec:
  type: NodePort
  selector:
    app: flask
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: flask-namespace
spec:
  type: NodePort
  selector:
    app: flask
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000
